/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_opencvedge_MainActivity */

#ifndef _Included_com_study_opencvedge_MyActivity
#define _Included_com_study_opencvedge_MyActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_opencvedge_MainActivity
 * Method:    ImgFun
 * Signature: ([III)[I
 */
//JNIEXPORT jintArray JNICALL Java_com_study_opencvedge_MainActivity_ImgFun(JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
